cuda-codeserver-v2:
  cap_drop:
    - AUDIT_CONTROL
    - BLOCK_SUSPEND
    - DAC_READ_SEARCH
    - IPC_LOCK
    - IPC_OWNER
    - LEASE
    - LINUX_IMMUTABLE
    - MAC_ADMIN
    - MAC_OVERRIDE
    - NET_ADMIN
    - NET_BROADCAST
    - SYSLOG
    - SYS_ADMIN
    - SYS_BOOT
    - SYS_MODULE
    - SYS_NICE
    - SYS_PACCT
    - SYS_PTRACE
    - SYS_RAWIO
    - SYS_RESOURCE
    - SYS_TIME
    - SYS_TTY_CONFIG
    - WAKE_ALARM
  container_name: cuda-codeserver-v2
  entrypoint:
    - /usr/bin/entrypoint.sh
    - --bind-addr
    - 0.0.0.0:8443
    - --cert
    - --disable-telemetry
    - .
  environment:
    - PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - NVARCH=x86_64
    - 'NVIDIA_REQUIRE_CUDA=cuda>=12.1 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471
      brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471
      brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471
      brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471
      brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526
      brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526
      brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526
      brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526'
    - NV_CUDA_CUDART_VERSION=12.1.105-1
    - NV_CUDA_COMPAT_PACKAGE=cuda-compat-12-1
    - CUDA_VERSION=12.1.1
    - LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    - NV_CUDA_LIB_VERSION=12.1.1-1
    - NV_NVTX_VERSION=12.1.105-1
    - NV_LIBNPP_VERSION=12.1.0.40-1
    - NV_LIBNPP_PACKAGE=libnpp-12-1=12.1.0.40-1
    - NV_LIBCUSPARSE_VERSION=12.1.0.106-1
    - NV_LIBCUBLAS_PACKAGE_NAME=libcublas-12-1
    - NV_LIBCUBLAS_VERSION=12.1.3.1-1
    - NV_LIBCUBLAS_PACKAGE=libcublas-12-1=12.1.3.1-1
    - NV_LIBNCCL_PACKAGE_NAME=libnccl2
    - NV_LIBNCCL_PACKAGE_VERSION=2.17.1-1
    - NCCL_VERSION=2.17.1-1
    - NV_LIBNCCL_PACKAGE=libnccl2=2.17.1-1+cuda12.1
    - NVIDIA_PRODUCT_NAME=CUDA
    - NV_CUDA_CUDART_DEV_VERSION=12.1.105-1
    - NV_NVML_DEV_VERSION=12.1.105-1
    - NV_LIBCUSPARSE_DEV_VERSION=12.1.0.106-1
    - NV_LIBNPP_DEV_VERSION=12.1.0.40-1
    - NV_LIBNPP_DEV_PACKAGE=libnpp-dev-12-1=12.1.0.40-1
    - NV_LIBCUBLAS_DEV_VERSION=12.1.3.1-1
    - NV_LIBCUBLAS_DEV_PACKAGE_NAME=libcublas-dev-12-1
    - NV_LIBCUBLAS_DEV_PACKAGE=libcublas-dev-12-1=12.1.3.1-1
    - NV_CUDA_NSIGHT_COMPUTE_VERSION=12.1.1-1
    - NV_CUDA_NSIGHT_COMPUTE_DEV_PACKAGE=cuda-nsight-compute-12-1=12.1.1-1
    - NV_NVPROF_VERSION=12.1.105-1
    - NV_NVPROF_DEV_PACKAGE=cuda-nvprof-12-1=12.1.105-1
    - NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
    - NV_LIBNCCL_DEV_PACKAGE_VERSION=2.17.1-1
    - NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.17.1-1+cuda12.1
    - LIBRARY_PATH=/usr/local/cuda/lib64/stubs
    - LANG=en_US.UTF-8
    - PROJECTS_ROOT=/home/coder/projects
    - ARCH=amd64
    - USER=coder
    - HOME=/home/coder
  hostname: d61bad361d19
  image: cuda-codeserver-v2:ubuntu20.04_cuda_12.1.1_codeserver_4.20.0
  ipc: host
  labels:
    build_version: 'Build-date:- 2024-01-18'
    maintainer: rayleizhu
    org.opencontainers.image.ref.name: ubuntu
    org.opencontainers.image.version: 20.04
  logging:
    driver: json-file
    options: {}
  mac_address: 02:42:ac:11:00:03
  network_mode: bridge
  ports:
    - 8443:8443/tcp
  restart: unless-stopped
  security_opt:
    - label=disable
  user: 1000:1000
  volumes:
    - /home/rayleizhu/codesever-home:/home/coder
    - /srv/dev-disk-by-uuid-53cdcff4-ecae-4851-b265-e2a91f5c147d/codeserver_hdd_storage:/mnt/hdd
  working_dir: /home/coder/projects
  